/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/owner/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 가게 조회
         * @description 로그인한 사업자 회원의 가게 정보를 조회합니다.
         */
        get: operations["getMyStore"];
        /**
         * 내 가게 수정
         * @description 로그인한 사업자 회원의 가게 정보를 수정합니다.
         */
        put: operations["updateMyStore"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/store/order-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 가게 주문 가능 일정 조회
         * @description 로그인한 사업자 회원의 가게 주문 가능 일정 설정을 조회합니다.
         */
        get: operations["getMyStoreOrderSchedule"];
        /**
         * 내 가게 주문 가능 일정 저장
         * @description 로그인한 사업자 회원의 가게 주문 가능 일정 설정을 저장합니다.
         */
        put: operations["saveMyStoreOrderSchedule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/store/menus/{menuId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 내 가게 메뉴 수정
         * @description 로그인한 사업자 회원의 가게 메뉴를 수정합니다.
         */
        put: operations["updateMenu"];
        post?: never;
        /**
         * 내 가게 메뉴 삭제
         * @description 로그인한 사업자 회원의 가게 메뉴를 삭제합니다.
         */
        delete: operations["deleteMenu"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/images/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이미지 업로드 presigned URL 발급
         * @description 이미지를 S3에 직접 업로드하기 위한 presigned URL을 발급합니다.
         */
        post: operations["createPresignedUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signup/customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 고객 회원가입 완료
         * @description 고객 추가 약관과 프로필 정보를 저장하고 가입을 완료합니다.
         */
        post: operations["signupCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signup/common": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 공통 회원가입
         * @description 소셜 계정, 공통 약관, 휴대폰 인증 정보를 저장합니다.
         */
        post: operations["signupCommon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signup/business": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 사업자 회원가입 신청
         * @description 사업자 추가 약관, 프로필, 사업자 인증 정보를 저장하고 승인 대기 상태로 전환합니다.
         */
        post: operations["signupBusiness"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phone-verifications/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증번호 발송
         * @description 휴대폰 번호로 인증번호를 발송합니다.
         */
        post: operations["sendCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phone-verifications/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증번호 확인
         * @description 휴대폰 인증번호를 확인하고 인증 완료 처리합니다.
         */
        post: operations["confirmCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 승인
         * @description 토스페이먼츠 결제 인증 성공 후 paymentKey, orderId, amount로 최종 결제 승인을 요청합니다.
         */
        post: operations["confirmPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/store/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 가게 메뉴 목록 조회
         * @description 로그인한 사업자 회원의 가게 메뉴 목록을 조회합니다.
         */
        get: operations["getMyStoreMenus"];
        put?: never;
        /**
         * 내 가게 메뉴 등록
         * @description 로그인한 사업자 회원의 가게에 메뉴를 등록합니다.
         */
        post: operations["createMenu"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 주문 내역 조회
         * @description 나의 주문 내역을 조회합니다.
         */
        get: operations["getOrderList"];
        put?: never;
        /**
         * 주문 생성
         * @description 로그인한 회원이 새로운 주문을 생성합니다.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 장바구니 메뉴 여러 개 한 번에 담기
         * @description 바텀 시트에서 선택한 여러 메뉴와 옵션을 한 번에 장바구니에 추가(또는 병합)합니다.
         */
        post: operations["addCartItems"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 장바구니 선택 항목 계산 및 주문 검증
         * @description 주문할 장바구니 항목들을 선택하여 총 결제 금액을 계산하고 단일 가게 제약을 검증합니다.
         */
        post: operations["calculateCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 사업자등록번호 검증
         * @description 국세청 API를 통해 사업자번호의 정상 영업 여부를 검증하고 토큰을 발급합니다.
         */
        post: operations["validateBusinessNumber"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Access token 재발급
         * @description Refresh token 쿠키로 Access token 쿠키를 재발급합니다.
         */
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 인증 쿠키를 삭제합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 주문 거절
         * @description 사업자가 본인 가게의 주문을 거절하고 결제 금액을 전액 환불합니다.
         */
        patch: operations["rejectOrder"];
        trace?: never;
    };
    "/api/orders/{orderId}/complete-pickup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 픽업 완료
         * @description 사업자가 본인 가게의 확정 주문을 픽업 완료 처리합니다.
         */
        patch: operations["completePickup"];
        trace?: never;
    };
    "/api/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 주문 취소
         * @description 로그인한 회원이 본인의 주문을 취소합니다.
         */
        patch: operations["cancelOrder"];
        trace?: never;
    };
    "/api/orders/{orderId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 주문 승인
         * @description 사업자가 본인 가게의 주문을 승인합니다.
         */
        patch: operations["acceptOrder"];
        trace?: never;
    };
    "/api/test/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 서버 헬스 체크
         * @description 서버가 정상적으로 실행 중이며, 통신이 가능한 상태인지 확인합니다.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 약관 목록 조회
         * @description 대상 유형별 활성 약관 목록을 조회합니다.
         */
        get: operations["getTerms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/{storeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가게 상세 정보 조회
         * @description 가게 ID를 통해 가게 상세 정보를 조회합니다.
         */
        get: operations["getStoreDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/{storeId}/pickup-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 특정 날짜의 픽업 가능 시간 및 수량 조회
         * @description 날짜를 선택하면 해당 날짜의 30분 단위 시간대별 잔여 수량을 반환합니다.
         */
        get: operations["getPickupTimes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/{storeId}/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가게 메뉴 목록 조회
         * @description 특정 가게의 전체 메뉴와 세부 옵션들을 조회합니다.
         */
        get: operations["getStoreMenus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가게 목록 검색
         * @description 위치, 카테고리, 예산, 픽업 시간 등 다양한 조건으로 가게를 검색합니다.
         */
        get: operations["searchStores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 사장님 주문 목록 조회
         * @description 탭(상태)별로 사장님의 주문 목록을 조회합니다.
         */
        get: operations["getOwnerOrderList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 사장님 주문 상세 조회
         * @description 특정 주문의 상세 정보(주문자, 주문상품, 결제 내역)를 조회합니다.
         */
        get: operations["getOwnerOrderDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주문 상세 내역 조회
         * @description 특정 주문의 상세 정보(메뉴, 옵션, 결제정보 등)를 조회합니다.
         */
        get: operations["getOrderDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 장바구니 목록 조회
         * @description 가게별로 그룹화된 장바구니 목록을 조회합니다.
         */
        get: operations["getCartList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth2/authorize/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 소셜 로그인 시작
         * @description 선택한 소셜 로그인 페이지로 이동합니다.
         */
        get: operations["authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 인증 정보 조회
         * @description Access token 쿠키 또는 Bearer 토큰으로 현재 로그인한 회원 정보를 조회합니다.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts/items/{cartItemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 장바구니 메뉴 삭제
         * @description 장바구니에서 특정 메뉴를 삭제합니다.
         */
        delete: operations["deleteCartItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DiscountDTO: {
            /**
             * Format: int32
             * @description 할인 조건 수량
             * @example 50
             */
            conditionQuantity?: number;
            /**
             * Format: int32
             * @description 할인율
             * @example 5
             */
            rate?: number;
        };
        LocationDTO: {
            /**
             * @description 도로명/지번 주소
             * @example 서울특별시 마포구 00로 00길 12
             */
            address: string;
            /**
             * @description 구
             * @example 마포구
             */
            district: string;
            /**
             * @description 동
             * @example 서교동
             */
            neighborhood?: string;
            /**
             * @description 상세주소
             * @example 3층
             */
            detailAddress?: string;
        };
        OwnerStoreUpdateRequest: {
            /**
             * @description 가게 대표 이미지 URL
             * @example https://groupeat-bucket.s3.ap-northeast-2.amazonaws.com/stores/1/main.jpg
             */
            imageUrl?: string;
            /**
             * @description 가게명
             * @example 데이브런치
             */
            storeName: string;
            /** @description 가게 위치 */
            location: components["schemas"]["LocationDTO"];
            /**
             * @description 가게 카테고리
             * @example SANDWICH_KIMBAP
             * @enum {string}
             */
            category: "SANDWICH_KIMBAP" | "DESSERT" | "BEVERAGE";
            /**
             * @description 전화번호
             * @example 010-1234-5678
             */
            phoneNumber: string;
            /**
             * @description 가게 한 줄 소개
             * @example 신선한 재료로 당일 제조하는 샌드위치 전문점입니다.
             */
            description?: string;
            /** @description 할인 정보 */
            discount?: components["schemas"]["DiscountDTO"];
        };
        ApiResponseOwnerStoreResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OwnerStoreResponse"];
        };
        OwnerStoreResponse: {
            /**
             * Format: int64
             * @description 가게 ID
             * @example 1
             */
            storeId?: number;
            /**
             * @description 가게 대표 이미지
             * @example https://groupeat-bucket.s3.ap-northeast-2.amazonaws.com/store1.jpg
             */
            imageUrl?: string;
            /**
             * @description 가게명
             * @example 데이브런치
             */
            storeName?: string;
            /** @description 가게 위치 */
            location?: components["schemas"]["LocationDTO"];
            /**
             * @description 가게 카테고리
             * @example SANDWICH_KIMBAP
             * @enum {string}
             */
            category?: "SANDWICH_KIMBAP" | "DESSERT" | "BEVERAGE";
            /**
             * @description 가게 카테고리명
             * @example 샌드위치&김밥
             */
            categoryName?: string;
            /**
             * @description 전화번호
             * @example 010-1234-5678
             */
            phoneNumber?: string;
            /**
             * @description 가게 한 줄 소개
             * @example 신선한 재료로 당일 제조하는 샌드위치 전문점입니다.
             */
            description?: string;
            /** @description 할인 정보 */
            discount?: components["schemas"]["DiscountDTO"];
        };
        DayScheduleRequest: {
            /**
             * @description 요일
             * @example MONDAY
             * @enum {string}
             */
            dayOfWeek: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
            /**
             * @description 주문 가능 여부
             * @example true
             */
            available: boolean;
            /**
             * Format: int32
             * @description 최소 주문 수량
             * @example 10
             */
            minOrderQuantity?: number;
            /**
             * Format: int32
             * @description 최대 주문 수량
             * @example 100
             */
            maxOrderQuantity?: number;
            /**
             * @description 픽업 시작 시간
             * @example 10:00
             */
            pickupOpenTime?: string;
            /**
             * @description 픽업 종료 시간
             * @example 17:00
             */
            pickupCloseTime?: string;
            /**
             * Format: int32
             * @description 픽업 시간 간격(분)
             * @example 30
             */
            intervalMinutes?: number;
        };
        OwnerStoreOrderScheduleRequest: {
            /**
             * Format: date
             * @description 일정 적용 시작일
             * @example 2026-05-20
             */
            startDate: string;
            /**
             * Format: date
             * @description 일정 적용 종료일
             * @example 2027-05-20
             */
            endDate: string;
            /**
             * Format: int32
             * @description 최소 주문 가능 기한(픽업 n일 전까지 주문 가능)
             * @example 3
             */
            minOrderDays: number;
            /** @description 요일별 주문 가능 일정. 포함되지 않은 요일은 휴무 처리됩니다. */
            days?: components["schemas"]["DayScheduleRequest"][];
        };
        ApiResponseOwnerStoreOrderScheduleResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OwnerStoreOrderScheduleResponse"];
        };
        DayScheduleResponse: {
            /**
             * @description 요일
             * @example MONDAY
             * @enum {string}
             */
            dayOfWeek?: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
            /**
             * @description 주문 가능 여부
             * @example true
             */
            available?: boolean;
            /**
             * Format: int32
             * @description 최소 주문 수량
             * @example 10
             */
            minOrderQuantity?: number;
            /**
             * Format: int32
             * @description 최대 주문 수량
             * @example 100
             */
            maxOrderQuantity?: number;
            /**
             * @description 픽업 시작 시간
             * @example 10:00
             */
            pickupOpenTime?: string;
            /**
             * @description 픽업 종료 시간
             * @example 17:00
             */
            pickupCloseTime?: string;
            /**
             * Format: int32
             * @description 픽업 시간 간격(분)
             * @example 30
             */
            intervalMinutes?: number;
        };
        OwnerStoreOrderScheduleResponse: {
            /**
             * Format: int64
             * @description 주문 가능 일정 ID
             * @example 1
             */
            scheduleId?: number;
            /**
             * Format: int64
             * @description 가게 ID
             * @example 1
             */
            storeId?: number;
            /**
             * Format: date
             * @description 일정 적용 시작일
             * @example 2026-05-20
             */
            startDate?: string;
            /**
             * Format: date
             * @description 일정 적용 종료일
             * @example 2027-05-20
             */
            endDate?: string;
            /**
             * Format: int32
             * @description 최소 주문 가능 기한(픽업 n일 전까지 주문 가능)
             * @example 3
             */
            minOrderDays?: number;
            /** @description 요일별 주문 가능 일정 */
            days?: components["schemas"]["DayScheduleResponse"][];
        };
        OwnerMenuRequest: {
            /**
             * @description 메뉴명
             * @example 햄치즈 샌드위치
             */
            name: string;
            /**
             * Format: int32
             * @description 기본 가격
             * @example 7800
             */
            basePrice: number;
            /**
             * @description 메뉴 설명
             * @example 햄과 치즈가 들어간 샌드위치입니다.
             */
            description?: string;
            /**
             * @description 메뉴 이미지 URL
             * @example https://groupeat-bucket.s3.ap-northeast-2.amazonaws.com/menus/1.jpg
             */
            imageUrl?: string;
        };
        ApiResponseOwnerMenuResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OwnerMenuResponse"];
        };
        OwnerMenuResponse: {
            /**
             * Format: int64
             * @description 메뉴 ID
             * @example 1
             */
            menuId?: number;
            /**
             * @description 메뉴명
             * @example 햄치즈 샌드위치
             */
            name?: string;
            /**
             * Format: int32
             * @description 기본 가격
             * @example 7800
             */
            basePrice?: number;
            /**
             * @description 메뉴 설명
             * @example 햄과 치즈가 들어간 샌드위치입니다.
             */
            description?: string;
            /**
             * @description 메뉴 이미지 URL
             * @example https://groupeat-bucket.s3.ap-northeast-2.amazonaws.com/menus/1.jpg
             */
            imageUrl?: string;
        };
        /**
         * @description 이미지 사용 도메인
         * @enum {string}
         */
        ImageUploadDomain: "STORE" | "MENU" | "PROFILE" | "REVIEW" | "BUSINESS_DOCUMENT";
        ImagePresignedUrlRequest: {
            /**
             * @description 원본 파일명
             * @example sandwich.jpg
             */
            fileName: string;
            /**
             * @description 이미지 Content-Type
             * @example image/jpeg
             */
            contentType: string;
        };
        ApiResponseImagePresignedUrlResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["ImagePresignedUrlResponse"];
        };
        ImagePresignedUrlResponse: {
            /** @description S3 업로드용 presigned URL */
            uploadUrl?: string;
            /** @description DB에 저장할 이미지 접근 URL */
            imageUrl?: string;
            /**
             * @description S3 object key
             * @example menus/2026/06/uuid.jpg
             */
            objectKey?: string;
        };
        CustomerSignupRequest: {
            /** Format: int64 */
            memberId: number;
            agreements: components["schemas"]["SignupAgreementRequest"][];
            name: string;
            email?: string;
            /** Format: date */
            birthDate?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "NONE";
        };
        SignupAgreementRequest: {
            /** Format: int64 */
            termsId: number;
            agreed: boolean;
        };
        ApiResponseCustomerSignupResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["CustomerSignupResponse"];
        };
        CustomerSignupResponse: {
            /** Format: int64 */
            memberId?: number;
            /** @enum {string} */
            memberType?: "CUSTOMER" | "BUSINESS";
            /** @enum {string} */
            memberStatus?: "SIGNUP_IN_PROGRESS" | "ACTIVE" | "BUSINESS_PENDING" | "BUSINESS_REJECTED" | "WITHDRAWN";
            message?: string;
        };
        CommonSignupRequest: {
            signupToken: string;
            /** @enum {string} */
            memberType: "CUSTOMER" | "BUSINESS";
            phoneNumber: string;
            agreements: components["schemas"]["SignupAgreementRequest"][];
        };
        ApiResponseCommonSignupResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["CommonSignupResponse"];
        };
        CommonSignupResponse: {
            /** Format: int64 */
            memberId?: number;
            /** @enum {string} */
            memberType?: "CUSTOMER" | "BUSINESS";
            nextStep?: string;
        };
        BusinessSignupRequest: {
            /** Format: int64 */
            memberId: number;
            agreements: components["schemas"]["SignupAgreementRequest"][];
            /** @enum {string} */
            businessType: "INDIVIDUAL" | "CORPORATION";
            representativeName: string;
            businessName: string;
            /** Format: date */
            openedDate: string;
            businessValidationToken: string;
            businessRegistrationCertificateUrl: string;
            email: string;
            /** Format: date */
            birthDate: string;
            /** @enum {string} */
            gender: "MALE" | "FEMALE" | "NONE";
        };
        ApiResponseBusinessSignupResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["BusinessSignupResponse"];
        };
        BusinessSignupResponse: {
            /** Format: int64 */
            memberId?: number;
            /** @enum {string} */
            memberType?: "CUSTOMER" | "BUSINESS";
            /** @enum {string} */
            memberStatus?: "SIGNUP_IN_PROGRESS" | "ACTIVE" | "BUSINESS_PENDING" | "BUSINESS_REJECTED" | "WITHDRAWN";
            /** @enum {string} */
            businessVerificationStatus?: "PENDING" | "APPROVED" | "REJECTED";
            message?: string;
        };
        PhoneVerificationSendRequest: {
            phoneNumber: string;
        };
        ApiResponsePhoneVerificationResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["PhoneVerificationResponse"];
        };
        PhoneVerificationResponse: {
            verified?: boolean;
            message?: string;
        };
        PhoneVerificationConfirmRequest: {
            phoneNumber: string;
            code: string;
        };
        PaymentConfirmRequest: {
            /**
             * @description 토스페이먼츠가 결제 인증 성공 후 발급한 결제 키
             * @example tgen_20260528123456AbCdEf
             */
            paymentKey: string;
            /**
             * @description 주문 생성 시 서버가 발급한 Toss Payments용 주문 ID
             * @example ORDER_1779722315381_5A617920
             */
            orderId: string;
            /**
             * Format: int32
             * @description 토스페이먼츠 승인 요청 금액
             * @example 423700
             */
            amount: number;
        };
        ApiResponsePaymentConfirmResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["PaymentConfirmResponse"];
        };
        PaymentConfirmResponse: {
            /**
             * Format: int64
             * @description 결제 DB 내부 ID
             * @example 1
             */
            paymentId?: number;
            /**
             * @description Toss Payments용 주문 ID
             * @example ORDER_1779722315381_5A617920
             */
            orderId?: string;
            /**
             * @description 토스페이먼츠 결제 키
             * @example tgen_20260528123456AbCdEf
             */
            paymentKey?: string;
            /**
             * Format: int32
             * @description 실제 PG 승인 금액
             * @example 423700
             */
            amount?: number;
            /**
             * @description 결제 상태
             * @example DONE
             * @enum {string}
             */
            status?: "READY" | "IN_PROGRESS" | "DONE" | "FAILED" | "CANCELED" | "PARTIAL_CANCELED";
            /**
             * Format: date
             * @description 결제 승인 완료 날짜
             * @example 2026-05-28
             */
            approvedDate?: string;
            /**
             * @description 결제 승인 완료 시간
             * @example 12:34:56
             */
            approvedTime?: string;
        };
        OrderCreateRequest: {
            /**
             * @description 주문할 장바구니 항목 ID 목록
             * @example [
             *       1,
             *       2
             *     ]
             */
            cartItemIds: number[];
            /**
             * @description 주문자명
             * @example 김동욱
             */
            customerName: string;
            /**
             * @description 연락처
             * @example 010-1234-5678
             */
            customerPhone: string;
            /**
             * @description 단체명 / 행사명 (선택)
             * @example CEOS 데모데이
             */
            groupName?: string;
            /**
             * @description 요청사항 (선택)
             * @example 맛있게 만들어 주세요.
             */
            requests?: string;
            /**
             * @description 결제 방식 (PREPAID: 선결제, ON_SITE: 현장결제)
             * @example PREPAID
             * @enum {string}
             */
            paymentMethod: "PREPAID" | "ON_SITE";
        };
        ApiResponseOrderCreateResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OrderCreateResponse"];
        };
        OrderCreateResponse: {
            /**
             * Format: int64
             * @description 생성된 주문의 고유 식별자 (PK)
             * @example 10
             */
            paymentId?: number;
            /**
             * @description 토스페이먼츠용 고유 주문 번호
             * @example ORDER_20260525_0001
             */
            orderId?: string;
            /**
             * Format: int32
             * @description 실제 결제할 금액 (선결제 100% 또는 현장결제 50% 적용 가격)
             * @example 372400
             */
            amount?: number;
            /**
             * @description 고객 이름
             * @example 김동욱
             */
            customerName?: string;
        };
        CartItemAddRequest: {
            /**
             * Format: int64
             * @description 가게 ID
             * @example 1
             */
            storeId: number;
            /**
             * Format: int64
             * @description 메뉴 ID
             * @example 1
             */
            menuId: number;
            /**
             * Format: int32
             * @description 수량
             * @example 56
             */
            quantity?: number;
            /** @description 선택한 옵션 ID 목록 (없으면 빈 리스트 또는 null) */
            optionIds?: number[];
            /**
             * Format: date
             * @description 픽업 날짜
             * @example 2026-04-23
             */
            pickupDate: string;
            /**
             * @description 픽업 시간
             * @example 10:00:00
             */
            pickupTime: string;
        };
        CartItemBulkAddRequest: {
            /** @description 장바구니에 담을 항목 리스트 */
            cartItems: components["schemas"]["CartItemAddRequest"][];
        };
        ApiResponseCartListResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["CartListResponse"];
        };
        CartItemDTO: {
            /**
             * Format: int64
             * @description 장바구니 항목 ID
             * @example 100
             */
            cartItemId?: number;
            /**
             * @description 메뉴명
             * @example 반반 세트 1
             */
            menuName?: string;
            /**
             * @description 선택한 옵션명 목록
             * @example [
             *       "햄치즈 샌드위치",
             *       "참치 김밥"
             *     ]
             */
            optionNames?: string[];
            /**
             * @description 메뉴 이미지
             * @example https://...
             */
            imageUrl?: string;
            /**
             * Format: int32
             * @description 수량
             * @example 56
             */
            quantity?: number;
            /**
             * Format: int32
             * @description 1인당 금액 (메뉴가 + 옵션가)
             * @example 7000
             */
            unitPrice?: number;
            /**
             * Format: int32
             * @description 항목별 할인 금액
             * @example 19600
             */
            discountAmount?: number;
            /**
             * Format: int32
             * @description 적용된 할인율 (%)
             * @example 5
             */
            discountRate?: number;
            /**
             * Format: int32
             * @description 총 금액 (할인 적용된 최종가)
             * @example 372400
             */
            finalPrice?: number;
        };
        CartListResponse: {
            /** @description 가게별로 그룹화된 장바구니 목록 */
            storeCarts?: components["schemas"]["StoreCartDTO"][];
        };
        StoreCartDTO: {
            /**
             * Format: int64
             * @description 가게 ID
             * @example 1
             */
            storeId?: number;
            /**
             * @description 가게명
             * @example 데이브런치
             */
            storeName?: string;
            /**
             * @description 가게 카테고리
             * @example 샌드위치&김밥
             */
            storeCategory?: string;
            /** @description 해당 가게에 담긴 메뉴 목록 */
            cartItems?: components["schemas"]["CartItemDTO"][];
            /**
             * Format: int32
             * @description 해당 가게의 주문 총 금액 (단순 합산)
             * @example 744800
             */
            storeTotalPrice?: number;
        };
        CartCalculateRequest: {
            /** @description 주문 할 장바구니의 CartItem ID 목록 */
            cartItemIds: number[];
        };
        ApiResponseCartCalculateResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["CartCalculateResponse"];
        };
        CalculatedItem: {
            /**
             * Format: int64
             * @description 장바구니 항목 ID
             */
            cartItemId?: number;
            /**
             * Format: int32
             * @description 수량
             */
            quantity?: number;
            /**
             * Format: int32
             * @description 1인당 단가 (메뉴가 + 옵션가)
             */
            unitPrice?: number;
            /**
             * Format: int32
             * @description 해당 항목 원가 총액
             */
            itemOriginalPrice?: number;
            /**
             * Format: int32
             * @description 해당 항목 할인 금액
             */
            itemDiscountAmount?: number;
            /**
             * Format: int32
             * @description 해당 항목 최종 금액
             */
            itemFinalPrice?: number;
        };
        CartCalculateResponse: {
            /**
             * Format: int64
             * @description 계산 대상 가게 ID
             * @example 1
             */
            storeId?: number;
            /**
             * Format: int32
             * @description 총 주문 수량
             * @example 112
             */
            totalQuantity?: number;
            /**
             * Format: int32
             * @description 할인 전 원가 총액
             * @example 784000
             */
            totalOriginalPrice?: number;
            /**
             * Format: int32
             * @description 적용된 총 할인 금액
             * @example 39200
             */
            totalDiscountAmount?: number;
            /**
             * Format: int32
             * @description 최종 결제 예정 금액 (원가 - 할인액)
             * @example 744800
             */
            finalPaymentAmount?: number;
            /** @description 계산에 포함된 메뉴들의 상세 정보 */
            calculatedItems?: components["schemas"]["CalculatedItem"][];
        };
        BusinessValidateRequest: {
            /**
             * @description 검증할 사업자등록번호 (하이픈 제외)
             * @example 1234567890
             */
            businessNumber: string;
        };
        ApiResponseBusinessValidateResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["BusinessValidateResponse"];
        };
        BusinessValidateResponse: {
            validationToken?: string;
        };
        ApiResponseTokenReissueResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["TokenReissueResponse"];
        };
        TokenReissueResponse: {
            message?: string;
        };
        ApiResponseLogoutResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["LogoutResponse"];
        };
        LogoutResponse: {
            message?: string;
        };
        ApiResponseOrderStatusChangeResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OrderStatusChangeResponse"];
        };
        OrderStatusChangeResponse: {
            /** Format: int64 */
            orderId?: number;
            /** @enum {string} */
            orderStatus?: "PENDING" | "PAID" | "ACCEPTED" | "COMPLETED" | "REJECTED" | "CANCELLED";
            /** Format: date */
            processedDate?: string;
            processedTime?: string;
        };
        OrderCancelRequest: {
            /**
             * @description 취소 사유
             * @example 일정 변경
             */
            cancelReason: string;
        };
        ApiResponseOrderCancelResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OrderCancelResponse"];
        };
        OrderCancelResponse: {
            /** Format: int64 */
            orderId?: number;
            /** @enum {string} */
            orderStatus?: "PENDING" | "PAID" | "ACCEPTED" | "COMPLETED" | "REJECTED" | "CANCELLED";
            /** Format: int32 */
            refundRate?: number;
            /** Format: int32 */
            refundAmount?: number;
            /** Format: date */
            cancelledDate?: string;
            cancelledTime?: string;
        };
        ApiResponseString: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: string;
        };
        ApiResponseListTermsResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["TermsResponse"][];
        };
        TermsResponse: {
            /** Format: int64 */
            termsId?: number;
            title?: string;
            content?: string;
            required?: boolean;
            targetType?: string;
            version?: string;
        };
        ApiResponseStoreDetailResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["StoreDetailResponse"];
        };
        StoreDetailResponse: {
            /**
             * Format: int64
             * @description 가게 ID
             * @example 1
             */
            storeId?: number;
            /**
             * @description 가게 대표 이미지
             * @example https://groupeat-bucket.s3.ap-northeast-2.amazonaws.com/store1.jpg
             */
            imageUrl?: string;
            /**
             * @description 가게명
             * @example 데이브런치
             */
            storeName?: string;
            /**
             * @description 가게 주소
             * @example 마포구 00로 00길
             */
            address?: string;
            /**
             * Format: double
             * @description 평균 별점
             * @example 4.7
             */
            reviewRating?: number;
            /**
             * Format: int32
             * @description 리뷰 개수
             * @example 128
             */
            reviewCount?: number;
            /**
             * @description 전화번호
             * @example 010-1234-5678
             */
            phoneNumber?: string;
            /**
             * @description 가게 한 줄 소개
             * @example 신선한 재료로 당일 제조하는 샌드위치 전문점입니다.
             */
            description?: string;
            /**
             * @description 휴무일
             * @example 화요일 휴무
             */
            closedDays?: string;
            /**
             * @description 픽업 시작 시간
             * @example 10:00
             */
            pickupOpenTime?: string;
            /**
             * @description 픽업 마감 시간
             * @example 17:00
             */
            pickupCloseTime?: string;
            /**
             * Format: int32
             * @description 주문 가능 기한
             * @example 3
             */
            minOrderDays?: number;
            /**
             * Format: int32
             * @description 할인율 기준
             * @example 50
             */
            discountConditionQuantity?: number;
            /**
             * Format: int32
             * @description 할인율
             * @example 5
             */
            discountRate?: number;
            /**
             * @description 주문 프로세스
             * @example 1. 예약 주문 2. 픽업 대기 3. 픽업 완료
             */
            orderProcess?: string;
        };
        ApiResponsePickupTimeResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["PickupTimeResponse"];
        };
        PickupTimeResponse: {
            /**
             * Format: date
             * @description 요청 날짜
             * @example 2026-04-23
             */
            date?: string;
            /**
             * Format: int32
             * @description 총 주문 가능 수량
             * @example 100
             */
            dailyAvailableQuantity?: number;
            /**
             * @description 픽업 시작 시간
             * @example 10:00
             */
            openTime?: string;
            /**
             * @description 픽업 종료 시간
             * @example 17:00
             */
            closeTime?: string;
            /**
             * Format: int32
             * @description 시간 간격(분)
             * @example 30
             */
            intervalMinutes?: number;
        };
        ApiResponseMenuListResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["MenuListResponse"];
        };
        MenuDetailDTO: {
            /**
             * Format: int64
             * @description 메뉴 ID
             * @example 1
             */
            menuId?: number;
            /**
             * @description 메뉴명
             * @example 반반 세트
             */
            name?: string;
            /**
             * Format: int32
             * @description 기본 가격
             * @example 7800
             */
            basePrice?: number;
            /**
             * @description 메뉴 설명
             * @example 샌드위치 반 + 김밥 반
             */
            description?: string;
            /**
             * @description 메뉴 이미지
             * @example https://...
             */
            imageUrl?: string;
            /** @description 옵션 그룹 목록 */
            optionGroups?: components["schemas"]["OptionGroupDTO"][];
        };
        MenuListResponse: {
            /** @description 메뉴 목록 */
            menus?: components["schemas"]["MenuDetailDTO"][];
        };
        OptionDTO: {
            /**
             * Format: int64
             * @description 세부 옵션 ID
             * @example 1
             */
            optionId?: number;
            /**
             * @description 옵션명
             * @example 햄치즈
             */
            name?: string;
            /**
             * Format: int32
             * @description 추가 금액
             * @example 900
             */
            additionalPrice?: number;
        };
        OptionGroupDTO: {
            /**
             * Format: int64
             * @description 옵션 그룹 ID
             * @example 1
             */
            optionGroupId?: number;
            /**
             * @description 옵션 그룹명
             * @example 샌드위치 선택 / 김밥 선택
             */
            name?: string;
            /**
             * @description 필수 선택 여부
             * @example true
             */
            isRequired?: boolean;
            /**
             * @description 다중 선택 가능 여부
             * @example false
             */
            isMultiple?: boolean;
            /** @description 세부 옵션 목록 */
            options?: components["schemas"]["OptionDTO"][];
        };
        StoreSearchCondition: {
            /**
             * @description 텍스트 검색어
             * @example 데이브런치
             */
            keyword?: string;
            /**
             * @description 위치 필터
             * @example 마포구
             * @enum {string}
             */
            region?: "GANGNAM" | "GANGDONG" | "GANGBUK" | "GANGSEO" | "GWANAK" | "GWANGJIN" | "GURO" | "GEUMCHEON" | "NOWON" | "DOBONG" | "DONGDAEMUN" | "DONGJAK" | "MAPO" | "SEODAEMUN" | "SEOCHO" | "SEONGDONG" | "SEONGBUK" | "SONGPA" | "YANGCHEON" | "YEONGDEUNGPO" | "YONGSAN" | "EUNPYEONG" | "JONGNO" | "JUNG" | "JUNGNANG";
            /**
             * Format: date
             * @description 픽업 날짜 필터 (단일 선택)
             * @example 2026-04-23
             */
            pickupDate?: string;
            /**
             * @description 픽업 시간 필터 (다중 선택 가능)
             * @example [
             *       "12:00:00",
             *       "13:00:00"
             *     ]
             */
            pickupTimes?: string[];
            /**
             * Format: int32
             * @description 주문 수량 필터
             * @example 50
             */
            quantity?: number;
            /**
             * Format: int32
             * @description 1인당 예산 필터
             * @example 10000
             */
            budget?: number;
            /**
             * @description 카테고리 필터
             * @example 샌드위치&김밥
             * @enum {string}
             */
            category?: "SANDWICH_KIMBAP" | "DESSERT" | "BEVERAGE";
            /**
             * @description 정렬 기준(기본값: NONE - 가나다 순)
             * @example NONE
             * @enum {string}
             */
            sortType?: "NONE" | "DISCOUNT_DESC" | "PRICE_ASC" | "PRICE_DESC" | "ORDER_DESC" | "RATING_DESC";
        };
        ApiResponseStoreListDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["StoreListDTO"];
        };
        StoreCardDTO: {
            /**
             * Format: int64
             * @description 가게 ID
             * @example 1
             */
            storeId?: number;
            /**
             * @description 대표 이미지
             * @example https://...
             */
            imageUrl?: string;
            /**
             * @description 가게명
             * @example 데이브런치
             */
            name?: string;
            /**
             * @description 카테고리
             * @example 샌드위치&김밥
             */
            category?: string;
            /**
             * Format: int32
             * @description 최소 가격
             * @example 7000
             */
            minPrice?: number;
            /**
             * Format: int32
             * @description 최대 가격
             * @example 12000
             */
            maxPrice?: number;
            /**
             * @description 연락처
             * @example 051-1234-5678
             */
            phoneNumber?: string;
            /**
             * Format: double
             * @description 별점
             * @example 4.7
             */
            rating?: number;
            /**
             * @description 픽업 시간
             * @example 10:00 ~ 17:00
             */
            pickupTimeRange?: string;
        };
        StoreListDTO: {
            /**
             * Format: int64
             * @description 검색된 전체 가게 수
             * @example 42
             */
            totalElements?: number;
            /** @description 가게 카드 리스트 */
            storeList?: components["schemas"]["StoreCardDTO"][];
        };
        ApiResponseOwnerOrderListDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OwnerOrderListDTO"];
        };
        OrderCardDTO: {
            /**
             * Format: int64
             * @description 주문 ID (PK)
             * @example 12
             */
            orderId?: number;
            /**
             * @description 주문 상태
             * @example PAID
             * @enum {string}
             */
            orderStatus?: "PENDING" | "PAID" | "ACCEPTED" | "COMPLETED" | "REJECTED" | "CANCELLED";
            /**
             * @description 주문자명
             * @example 김동욱
             */
            customerName?: string;
            /**
             * @description 주문 단체명
             * @example CEOS 데모데이
             */
            groupName?: string;
            /**
             * Format: date
             * @description 픽업 날짜
             * @example 2026-06-21
             */
            pickupDate?: string;
            /**
             * @description 픽업 시간
             * @example 13:00:00
             */
            pickupTime?: string;
            /**
             * Format: int32
             * @description 총 금액 (할인 적용된 최종 금액)
             * @example 35000
             */
            totalAmount?: number;
            /** @description 주문 상품 리스트 (메뉴명과 수량 분리) */
            items?: components["schemas"]["OrderCardItemDTO"][];
            /**
             * @description 재주문 여부
             * @example false
             */
            isReorder?: boolean;
            /**
             * @description 결제 방식 (확정 탭에서만 노출, 그 외엔 null)
             * @example PREPAID
             * @enum {string}
             */
            paymentMethod?: "PREPAID" | "ON_SITE";
            /**
             * Format: int32
             * @description 승인 마감까지 남은 시간 (대기 중 탭에서만 노출, 그 외엔 null)
             * @example 18
             */
            remainingHours?: number;
        };
        OrderCardItemDTO: {
            /**
             * @description 주문 메뉴명
             * @example 반반 세트
             */
            menuName?: string;
            /**
             * Format: int32
             * @description 주문 수량
             * @example 2
             */
            quantity?: number;
        };
        OwnerOrderListDTO: {
            /**
             * Format: int64
             * @description 조건에 해당하는 주문 개수
             * @example 5
             */
            totalElements?: number;
            /** @description 주문 카드 리스트 */
            orderList?: components["schemas"]["OrderCardDTO"][];
            /**
             * @description 다음 페이지 존재 여부 (무한 스크롤용)
             * @example true
             */
            hasNext?: boolean;
            /**
             * Format: int64
             * @description 다음 커서 ID (마지막 주문의 PK ID)
             * @example 42
             */
            nextCursor?: number;
        };
        ApiResponseOrderDetailDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OrderDetailDTO"];
        };
        OrderDetailDTO: {
            /** @description 주문자 정보 */
            ordererInfo?: components["schemas"]["OrdererInfoDTO"];
            /** @description 주문 상품 정보 목록 */
            orderMenus?: components["schemas"]["OrderMenuDTO"][];
            /** @description 결제 정보 */
            paymentInfo?: components["schemas"]["PaymentInfoDTO"];
        };
        OrderMenuDTO: {
            /**
             * @description 주문 메뉴 및 옵션
             * @example 반반 세트
             */
            menuName?: string;
            /** @description 선택한 옵션 목록 */
            options?: components["schemas"]["OrderMenuOptionDTO"][];
            /**
             * Format: int32
             * @description 주문 수량
             * @example 2
             */
            quantity?: number;
            /**
             * @description 메뉴 이미지 URL
             * @example https://image.url/menu.png
             */
            menuImageUrl?: string;
            /**
             * Format: int32
             * @description 할인율(%)
             * @example 10
             */
            discountRate?: number;
            /**
             * Format: int32
             * @description 해당 메뉴 총 금액
             * @example 30000
             */
            totalAmount?: number;
        };
        OrderMenuOptionDTO: {
            /**
             * @description 옵션명
             * @example 햄치즈 샌드위치
             */
            optionName?: string;
        };
        OrdererInfoDTO: {
            /**
             * @description 주문자명
             * @example 김동욱
             */
            customerName?: string;
            /**
             * @description 주문 단체명
             * @example CEOS 데모데이
             */
            groupName?: string;
            /**
             * @description 연락처
             * @example 010-1234-5678
             */
            phoneNumber?: string;
            /**
             * Format: date
             * @description 주문 일자
             * @example 2026-06-20
             */
            orderDate?: string;
            /**
             * @description 요청사항
             * @example 픽업 시간에 맞춰서 준비해 주세요.
             */
            requests?: string;
        };
        PaymentInfoDTO: {
            /**
             * @description 결제 방식
             * @example PREPAID
             * @enum {string}
             */
            paymentMethod?: "PREPAID" | "ON_SITE";
            /**
             * @description 결제 수단
             * @example 토스페이
             * @enum {string}
             */
            paymentMeans?: "TOSS";
            /**
             * Format: int32
             * @description 1인당 금액(소수점 삭제)
             * @example 7000
             */
            perPersonAmount?: number;
            /**
             * Format: int32
             * @description 총 할인율(%)
             * @example 10
             */
            discountRate?: number;
            /**
             * Format: int32
             * @description 총 할인 금액
             * @example 5000
             */
            totalDiscountAmount?: number;
            /**
             * Format: int32
             * @description 할인 전 총 금액
             * @example 35000
             */
            originalTotalAmount?: number;
            /**
             * Format: int32
             * @description 최종 결제 금액
             * @example 30000
             */
            finalPaymentAmount?: number;
        };
        ApiResponseOrderListResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OrderListResponse"];
        };
        OrderListResponse: {
            /**
             * Format: int64
             * @description 조건에 해당하는 조회 목록 개수
             * @example 5
             */
            totalElements?: number;
            /** @description 주문 카드 리스트 */
            orderList?: components["schemas"]["OrderCardDTO"][];
            /**
             * @description 다음 페이지 존재 여부 (무한 스크롤용)
             * @example true
             */
            hasNext?: boolean;
            /**
             * Format: int64
             * @description 다음 커서 ID (마지막 주문의 PK ID)
             * @example 42
             */
            nextCursor?: number;
        };
        ApiResponseAuthenticatedMemberResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["AuthenticatedMemberResponse"];
        };
        AuthenticatedMemberResponse: {
            /** Format: int64 */
            memberId?: number;
            /** @enum {string} */
            memberType?: "CUSTOMER" | "BUSINESS";
            /** @enum {string} */
            memberStatus?: "SIGNUP_IN_PROGRESS" | "ACTIVE" | "BUSINESS_PENDING" | "BUSINESS_REJECTED" | "WITHDRAWN";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMyStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOwnerStoreResponse"];
                };
            };
        };
    };
    updateMyStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerStoreUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOwnerStoreResponse"];
                };
            };
        };
    };
    getMyStoreOrderSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOwnerStoreOrderScheduleResponse"];
                };
            };
        };
    };
    saveMyStoreOrderSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerStoreOrderScheduleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOwnerStoreOrderScheduleResponse"];
                };
            };
        };
    };
    updateMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerMenuRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOwnerMenuResponse"];
                };
            };
        };
    };
    deleteMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    createPresignedUrl: {
        parameters: {
            query: {
                /** @description 이미지 사용 도메인 */
                domain: components["schemas"]["ImageUploadDomain"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImagePresignedUrlRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseImagePresignedUrlResponse"];
                };
            };
        };
    };
    signupCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerSignupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCustomerSignupResponse"];
                };
            };
        };
    };
    signupCommon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommonSignupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCommonSignupResponse"];
                };
            };
        };
    };
    signupBusiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessSignupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBusinessSignupResponse"];
                };
            };
        };
    };
    sendCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneVerificationSendRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePhoneVerificationResponse"];
                };
            };
        };
    };
    confirmCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneVerificationConfirmRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePhoneVerificationResponse"];
                };
            };
        };
    };
    confirmPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentConfirmRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaymentConfirmResponse"];
                };
            };
        };
    };
    getMyStoreMenus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMenuListResponse"];
                };
            };
        };
    };
    createMenu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerMenuRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOwnerMenuResponse"];
                };
            };
        };
    };
    getOrderList: {
        parameters: {
            query?: {
                /** @description 정렬 필터 타입 */
                filter?: "ALL" | "IN_PROGRESS" | "PAST";
                /** @description 마지막으로 조회된 주문 ID (최초 조회 시 생략) */
                lastOrderId?: number;
                /** @description 한 번에 가져올 데이터 개수 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderListResponse"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderCreateResponse"];
                };
            };
        };
    };
    addCartItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemBulkAddRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCartListResponse"];
                };
            };
        };
    };
    calculateCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartCalculateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCartCalculateResponse"];
                };
            };
        };
    };
    validateBusinessNumber: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessValidateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBusinessValidateResponse"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenReissueResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLogoutResponse"];
                };
            };
        };
    };
    rejectOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 거절할 주문 ID */
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderStatusChangeResponse"];
                };
            };
        };
    };
    completePickup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 픽업 완료 처리할 주문 ID */
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderStatusChangeResponse"];
                };
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 취소할 주문 ID */
                orderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCancelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderCancelResponse"];
                };
            };
        };
    };
    acceptOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 승인할 주문 ID */
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderStatusChangeResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    getTerms: {
        parameters: {
            query: {
                targetType: "COMMON" | "CUSTOMER" | "BUSINESS";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTermsResponse"];
                };
            };
        };
    };
    getStoreDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseStoreDetailResponse"];
                };
            };
        };
    };
    getPickupTimes: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                storeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePickupTimeResponse"];
                };
            };
        };
    };
    getStoreMenus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMenuListResponse"];
                };
            };
        };
    };
    searchStores: {
        parameters: {
            query: {
                condition: components["schemas"]["StoreSearchCondition"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseStoreListDTO"];
                };
            };
        };
    };
    getOwnerOrderList: {
        parameters: {
            query: {
                tab: "WAITING" | "CONFIRMED" | "PAST";
                lastOrderId?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOwnerOrderListDTO"];
                };
            };
        };
    };
    getOwnerOrderDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 조회할 주문 ID */
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderDetailDTO"];
                };
            };
        };
    };
    getOrderDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 조회할 주문 ID */
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderDetailDTO"];
                };
            };
        };
    };
    getCartList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCartListResponse"];
                };
            };
        };
    };
    authorize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthenticatedMemberResponse"];
                };
            };
        };
    };
    deleteCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartItemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
}
