/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/signup/customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 고객 회원가입 완료
         * @description 고객 추가 약관과 프로필 정보를 저장하고 가입을 완료합니다.
         */
        post: operations["signupCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signup/common": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 공통 회원가입
         * @description 소셜 계정, 공통 약관, 휴대폰 인증 정보를 저장합니다.
         */
        post: operations["signupCommon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signup/business": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 사업자 회원가입 신청
         * @description 사업자 추가 약관, 프로필, 사업자 인증 정보를 저장하고 승인 대기 상태로 전환합니다.
         */
        post: operations["signupBusiness"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phone-verifications/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증번호 발송
         * @description 휴대폰 번호로 인증번호를 발송합니다.
         */
        post: operations["sendCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phone-verifications/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증번호 확인
         * @description 휴대폰 인증번호를 확인하고 인증 완료 처리합니다.
         */
        post: operations["confirmCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 승인
         * @description 토스페이먼츠 결제 인증 성공 후 paymentKey, orderId, amount로 최종 결제 승인을 요청합니다.
         */
        post: operations["confirmPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 주문 내역 조회
         * @description 나의 주문 내역을 조회합니다.
         */
        get: operations["getOrderList"];
        put?: never;
        /**
         * 주문 생성
         * @description 로그인한 회원이 새로운 주문을 생성합니다.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 장바구니 메뉴 담기
         * @description 장바구니에 새로운 메뉴와 옵션을 추가합니다.
         */
        post: operations["addCartItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 장바구니 선택 항목 계산 및 주문 검증
         * @description 주문할 장바구니 항목들을 선택하여 총 결제 금액을 계산하고 단일 가게 제약을 검증합니다.
         */
        post: operations["calculateCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Access token 재발급
         * @description Refresh token 쿠키로 Access token 쿠키를 재발급합니다.
         */
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 인증 쿠키를 삭제합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 주문 거절
         * @description 사업자가 본인 가게의 주문을 거절하고 결제 금액을 전액 환불합니다.
         */
        patch: operations["rejectOrder"];
        trace?: never;
    };
    "/api/orders/{orderId}/complete-pickup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 픽업 완료
         * @description 사업자가 본인 가게의 확정 주문을 픽업 완료 처리합니다.
         */
        patch: operations["completePickup"];
        trace?: never;
    };
    "/api/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 주문 취소
         * @description 로그인한 회원이 본인의 주문을 취소합니다.
         */
        patch: operations["cancelOrder"];
        trace?: never;
    };
    "/api/orders/{orderId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 주문 승인
         * @description 사업자가 본인 가게의 주문을 승인합니다.
         */
        patch: operations["acceptOrder"];
        trace?: never;
    };
    "/api/test/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 서버 헬스 체크
         * @description 서버가 정상적으로 실행 중이며, 통신이 가능한 상태인지 확인합니다.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 약관 목록 조회
         * @description 대상 유형별 활성 약관 목록을 조회합니다.
         */
        get: operations["getTerms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/{storeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가게 상세 정보 조회
         * @description 가게 ID를 통해 가게 상세 정보를 조회합니다.
         */
        get: operations["getStoreDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/{storeId}/pickup-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 특정 날짜의 픽업 가능 시간 및 수량 조회
         * @description 날짜를 선택하면 해당 날짜의 30분 단위 시간대별 잔여 수량을 반환합니다.
         */
        get: operations["getPickupTimes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/{storeId}/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가게 메뉴 목록 조회
         * @description 특정 가게의 전체 메뉴와 세부 옵션들을 조회합니다.
         */
        get: operations["getStoreMenus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가게 목록 검색
         * @description 위치, 카테고리, 예산, 픽업 시간 등 다양한 조건으로 가게를 검색합니다.
         */
        get: operations["searchStores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주문 상세 내역 조회
         * @description 특정 주문의 상세 정보(메뉴, 옵션, 결제정보 등)를 조회합니다.
         */
        get: operations["getOrderDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 장바구니 목록 조회
         * @description 가게별로 그룹화된 장바구니 목록을 조회합니다.
         */
        get: operations["getCartList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth2/authorize/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 소셜 로그인 시작
         * @description 선택한 소셜 로그인 페이지로 이동합니다.
         */
        get: operations["authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 인증 정보 조회
         * @description Access token 쿠키 또는 Bearer 토큰으로 현재 로그인한 회원 정보를 조회합니다.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carts/items/{cartItemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 장바구니 메뉴 삭제
         * @description 장바구니에서 특정 메뉴를 삭제합니다.
         */
        delete: operations["deleteCartItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CustomerSignupRequest: {
            /** Format: int64 */
            memberId: number;
            agreements: components["schemas"]["SignupAgreementRequest"][];
            name: string;
            email?: string;
            /** Format: date */
            birthDate?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "NONE";
        };
        SignupAgreementRequest: {
            /** Format: int64 */
            termsId: number;
            agreed: boolean;
        };
        ApiResponseCustomerSignupResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["CustomerSignupResponse"];
        };
        CustomerSignupResponse: {
            /** Format: int64 */
            memberId?: number;
            /** @enum {string} */
            memberType?: "CUSTOMER" | "BUSINESS";
            /** @enum {string} */
            memberStatus?: "SIGNUP_IN_PROGRESS" | "ACTIVE" | "BUSINESS_PENDING" | "BUSINESS_REJECTED" | "WITHDRAWN";
            message?: string;
        };
        CommonSignupRequest: {
            signupToken: string;
            /** @enum {string} */
            memberType: "CUSTOMER" | "BUSINESS";
            phoneNumber: string;
            agreements: components["schemas"]["SignupAgreementRequest"][];
        };
        ApiResponseCommonSignupResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["CommonSignupResponse"];
        };
        CommonSignupResponse: {
            /** Format: int64 */
            memberId?: number;
            /** @enum {string} */
            memberType?: "CUSTOMER" | "BUSINESS";
            nextStep?: string;
        };
        BusinessSignupRequest: {
            /** Format: int64 */
            memberId: number;
            agreements: components["schemas"]["SignupAgreementRequest"][];
            /** @enum {string} */
            businessType: "INDIVIDUAL" | "CORPORATION";
            representativeName: string;
            businessName: string;
            /** Format: date */
            openedDate: string;
            businessRegistrationNumber: string;
            businessRegistrationCertificateUrl: string;
            email: string;
            /** Format: int32 */
            age: number;
            /** @enum {string} */
            gender: "MALE" | "FEMALE" | "NONE";
        };
        ApiResponseBusinessSignupResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["BusinessSignupResponse"];
        };
        BusinessSignupResponse: {
            /** Format: int64 */
            memberId?: number;
            /** @enum {string} */
            memberType?: "CUSTOMER" | "BUSINESS";
            /** @enum {string} */
            memberStatus?: "SIGNUP_IN_PROGRESS" | "ACTIVE" | "BUSINESS_PENDING" | "BUSINESS_REJECTED" | "WITHDRAWN";
            /** @enum {string} */
            businessVerificationStatus?: "PENDING" | "APPROVED" | "REJECTED";
            message?: string;
        };
        PhoneVerificationSendRequest: {
            phoneNumber: string;
        };
        ApiResponsePhoneVerificationResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["PhoneVerificationResponse"];
        };
        PhoneVerificationResponse: {
            verified?: boolean;
            message?: string;
        };
        PhoneVerificationConfirmRequest: {
            phoneNumber: string;
            code: string;
        };
        PaymentConfirmRequest: {
            /**
             * @description 토스페이먼츠가 결제 인증 성공 후 발급한 결제 키
             * @example tgen_20260528123456AbCdEf
             */
            paymentKey: string;
            /**
             * @description 주문 생성 시 서버가 발급한 Toss Payments용 주문 ID
             * @example ORDER_1779722315381_5A617920
             */
            orderId: string;
            /**
             * Format: int32
             * @description 토스페이먼츠 승인 요청 금액
             * @example 423700
             */
            amount: number;
        };
        ApiResponsePaymentConfirmResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["PaymentConfirmResponse"];
        };
        PaymentConfirmResponse: {
            /**
             * Format: int64
             * @description 결제 DB 내부 ID
             * @example 1
             */
            paymentId?: number;
            /**
             * @description Toss Payments용 주문 ID
             * @example ORDER_1779722315381_5A617920
             */
            orderId?: string;
            /**
             * @description 토스페이먼츠 결제 키
             * @example tgen_20260528123456AbCdEf
             */
            paymentKey?: string;
            /**
             * Format: int32
             * @description 실제 PG 승인 금액
             * @example 423700
             */
            amount?: number;
            /**
             * @description 결제 상태
             * @example DONE
             * @enum {string}
             */
            status?: "READY" | "IN_PROGRESS" | "DONE" | "FAILED" | "CANCELED" | "PARTIAL_CANCELED";
            /**
             * Format: date-time
             * @description 결제 승인 완료 시각
             */
            approvedAt?: string;
        };
        OrderCreateRequest: {
            /**
             * @description 주문할 장바구니 항목 ID 목록
             * @example [
             *       1,
             *       2
             *     ]
             */
            cartItemIds: number[];
            /**
             * @description 주문자명
             * @example 김동욱
             */
            customerName: string;
            /**
             * @description 연락처
             * @example 010-1234-5678
             */
            customerPhone: string;
            /**
             * @description 단체명 / 행사명 (선택)
             * @example CEOS 데모데이
             */
            groupName?: string;
            /**
             * @description 요청사항 (선택)
             * @example 맛있게 만들어 주세요.
             */
            requests?: string;
            /**
             * @description 결제 방식 (PREPAID: 선결제, ON_SITE: 현장결제)
             * @example PREPAID
             * @enum {string}
             */
            paymentMethod: "PREPAID" | "ON_SITE";
        };
        ApiResponseOrderCreateResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OrderCreateResponse"];
        };
        OrderCreateResponse: {
            /**
             * Format: int64
             * @description 생성된 주문의 고유 식별자 (PK)
             * @example 10
             */
            paymentId?: number;
            /**
             * @description 토스페이먼츠용 고유 주문 번호
             * @example ORDER_20260525_0001
             */
            orderId?: string;
            /**
             * Format: int32
             * @description 실제 결제할 금액 (선결제 100% 또는 현장결제 50% 적용 가격)
             * @example 372400
             */
            amount?: number;
            /**
             * @description 고객 이름
             * @example 김동욱
             */
            customerName?: string;
        };
        CartItemAddRequest: {
            /**
             * Format: int64
             * @description 가게 ID
             * @example 1
             */
            storeId: number;
            /**
             * Format: int64
             * @description 메뉴 ID
             * @example 1
             */
            menuId: number;
            /**
             * Format: int32
             * @description 수량
             * @example 56
             */
            quantity?: number;
            /** @description 선택한 옵션 ID 목록 (없으면 빈 리스트 또는 null) */
            optionIds?: number[];
            /**
             * Format: date
             * @description 픽업 날짜
             * @example 2026-04-23
             */
            pickupDate: string;
            /**
             * @description 픽업 시간
             * @example 10:00:00
             */
            pickupTime: string;
        };
        ApiResponseCartListResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["CartListResponse"];
        };
        CartItemDTO: {
            /**
             * Format: int64
             * @description 장바구니 항목 ID
             * @example 100
             */
            cartItemId?: number;
            /**
             * @description 메뉴명 및 옵션 요약 (UI 노출용)
             * @example 반반 세트 1 (햄치즈 샌드위치, 참치 김밥)
             */
            menuSummary?: string;
            /**
             * @description 메뉴 이미지
             * @example https://...
             */
            imageUrl?: string;
            /**
             * Format: int32
             * @description 수량
             * @example 56
             */
            quantity?: number;
            /**
             * Format: int32
             * @description 1인당 금액 (메뉴가 + 옵션가)
             * @example 7000
             */
            unitPrice?: number;
            /**
             * Format: int32
             * @description 항목별 할인 금액
             * @example 19600
             */
            discountAmount?: number;
            /**
             * Format: int32
             * @description 적용된 할인율 (%)
             * @example 5
             */
            discountRate?: number;
            /**
             * Format: int32
             * @description 총 금액 (할인 적용된 최종가)
             * @example 372400
             */
            finalPrice?: number;
        };
        CartListResponse: {
            /** @description 가게별로 그룹화된 장바구니 목록 */
            storeCarts?: components["schemas"]["StoreCartDTO"][];
        };
        StoreCartDTO: {
            /**
             * Format: int64
             * @description 가게 ID
             * @example 1
             */
            storeId?: number;
            /**
             * @description 가게명
             * @example 데이브런치
             */
            storeName?: string;
            /** @description 해당 가게에 담긴 메뉴 목록 */
            cartItems?: components["schemas"]["CartItemDTO"][];
            /**
             * Format: int32
             * @description 해당 가게의 주문 총 금액 (단순 합산)
             * @example 744800
             */
            storeTotalPrice?: number;
        };
        CartCalculateRequest: {
            /** @description 주문 할 장바구니의 CartItem ID 목록 */
            cartItemIds: number[];
        };
        ApiResponseCartCalculateResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["CartCalculateResponse"];
        };
        CalculatedItem: {
            /**
             * Format: int64
             * @description 장바구니 항목 ID
             */
            cartItemId?: number;
            /**
             * Format: int32
             * @description 수량
             */
            quantity?: number;
            /**
             * Format: int32
             * @description 1인당 단가 (메뉴가 + 옵션가)
             */
            unitPrice?: number;
            /**
             * Format: int32
             * @description 해당 항목 원가 총액
             */
            itemOriginalPrice?: number;
            /**
             * Format: int32
             * @description 해당 항목 할인 금액
             */
            itemDiscountAmount?: number;
            /**
             * Format: int32
             * @description 해당 항목 최종 금액
             */
            itemFinalPrice?: number;
        };
        CartCalculateResponse: {
            /**
             * Format: int64
             * @description 계산 대상 가게 ID
             * @example 1
             */
            storeId?: number;
            /**
             * Format: int32
             * @description 총 주문 수량
             * @example 112
             */
            totalQuantity?: number;
            /**
             * Format: int32
             * @description 할인 전 원가 총액
             * @example 784000
             */
            totalOriginalPrice?: number;
            /**
             * Format: int32
             * @description 적용된 총 할인 금액
             * @example 39200
             */
            totalDiscountAmount?: number;
            /**
             * Format: int32
             * @description 최종 결제 예정 금액 (원가 - 할인액)
             * @example 744800
             */
            finalPaymentAmount?: number;
            /** @description 계산에 포함된 메뉴들의 상세 정보 */
            calculatedItems?: components["schemas"]["CalculatedItem"][];
        };
        ApiResponseTokenReissueResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["TokenReissueResponse"];
        };
        TokenReissueResponse: {
            message?: string;
        };
        ApiResponseLogoutResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["LogoutResponse"];
        };
        LogoutResponse: {
            message?: string;
        };
        OrderRejectRequest: {
            /**
             * @description 거절 사유
             * @example 재료 소진
             */
            rejectReason: string;
        };
        ApiResponseOrderStatusChangeResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OrderStatusChangeResponse"];
        };
        OrderStatusChangeResponse: {
            /** Format: int64 */
            orderId?: number;
            /** @enum {string} */
            orderStatus?: "PENDING" | "PAID" | "ACCEPTED" | "COMPLETED" | "REJECTED" | "CANCELLED";
            /** Format: date-time */
            processedAt?: string;
        };
        OrderCancelRequest: {
            /**
             * @description 취소 사유
             * @example 일정 변경
             */
            cancelReason: string;
        };
        ApiResponseOrderCancelResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OrderCancelResponse"];
        };
        OrderCancelResponse: {
            /** Format: int64 */
            orderId?: number;
            /** @enum {string} */
            orderStatus?: "PENDING" | "PAID" | "ACCEPTED" | "COMPLETED" | "REJECTED" | "CANCELLED";
            /** Format: int32 */
            refundRate?: number;
            /** Format: int32 */
            refundAmount?: number;
            /** Format: date-time */
            cancelledAt?: string;
        };
        ApiResponseString: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: string;
        };
        ApiResponseListTermsResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["TermsResponse"][];
        };
        TermsResponse: {
            /** Format: int64 */
            termsId?: number;
            title?: string;
            content?: string;
            required?: boolean;
            targetType?: string;
            version?: string;
        };
        ApiResponseStoreDetailResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["StoreDetailResponse"];
        };
        StoreDetailResponse: {
            /**
             * Format: int64
             * @description 가게 ID
             * @example 1
             */
            storeId?: number;
            /**
             * @description 가게 대표 이미지
             * @example https://groupeat-bucket.s3.ap-northeast-2.amazonaws.com/store1.jpg
             */
            imageUrl?: string;
            /**
             * @description 가게명
             * @example 데이브런치
             */
            storeName?: string;
            /**
             * @description 가게 주소
             * @example 마포구 00로 00길
             */
            address?: string;
            /**
             * Format: double
             * @description 평균 별점
             * @example 4.7
             */
            reviewRating?: number;
            /**
             * Format: int32
             * @description 리뷰 개수
             * @example 128
             */
            reviewCount?: number;
            /**
             * @description 전화번호
             * @example 010-1234-5678
             */
            phoneNumber?: string;
            /**
             * @description 가게 한 줄 소개
             * @example 신선한 재료로 당일 제조하는 샌드위치 전문점입니다.
             */
            description?: string;
            /**
             * @description 휴무일
             * @example 화요일 휴무
             */
            closedDays?: string;
            /**
             * @description 픽업 시작 시간
             * @example 10:00
             */
            pickupOpenTime?: string;
            /**
             * @description 픽업 마감 시간
             * @example 17:00
             */
            pickupCloseTime?: string;
            /**
             * Format: int32
             * @description 주문 가능 기한
             * @example 3
             */
            minOrderDays?: number;
            /**
             * Format: int32
             * @description 할인율 기준
             * @example 50
             */
            discountConditionQuantity?: number;
            /**
             * Format: int32
             * @description 할인율
             * @example 5
             */
            discountRate?: number;
            /**
             * @description 주문 프로세스
             * @example 1. 예약 주문 2. 픽업 대기 3. 픽업 완료
             */
            orderProcess?: string;
        };
        ApiResponsePickupTimeResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["PickupTimeResponse"];
        };
        PickupTimeResponse: {
            /**
             * Format: date
             * @description 요청 날짜
             * @example 2026-04-23
             */
            date?: string;
            /**
             * Format: int32
             * @description 총 주문 가능 수량
             * @example 100
             */
            dailyAvailableQuantity?: number;
            /**
             * @description 픽업 시작 시간
             * @example 10:00
             */
            openTime?: string;
            /**
             * @description 픽업 종료 시간
             * @example 17:00
             */
            closeTime?: string;
            /**
             * Format: int32
             * @description 시간 간격(분)
             * @example 30
             */
            intervalMinutes?: number;
        };
        ApiResponseMenuListResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["MenuListResponse"];
        };
        MenuDetailDTO: {
            /**
             * Format: int64
             * @description 메뉴 ID
             * @example 1
             */
            menuId?: number;
            /**
             * @description 메뉴명
             * @example 반반 세트
             */
            name?: string;
            /**
             * Format: int32
             * @description 기본 가격
             * @example 7800
             */
            basePrice?: number;
            /**
             * @description 메뉴 설명
             * @example 샌드위치 반 + 김밥 반
             */
            description?: string;
            /**
             * @description 메뉴 이미지
             * @example https://...
             */
            imageUrl?: string;
            /** @description 옵션 그룹 목록 */
            optionGroups?: components["schemas"]["OptionGroupDTO"][];
        };
        MenuListResponse: {
            /** @description 메뉴 목록 */
            menus?: components["schemas"]["MenuDetailDTO"][];
        };
        OptionDTO: {
            /**
             * Format: int64
             * @description 세부 옵션 ID
             * @example 1
             */
            optionId?: number;
            /**
             * @description 옵션명
             * @example 햄치즈
             */
            name?: string;
            /**
             * Format: int32
             * @description 추가 금액
             * @example 900
             */
            additionalPrice?: number;
        };
        OptionGroupDTO: {
            /**
             * Format: int64
             * @description 옵션 그룹 ID
             * @example 1
             */
            optionGroupId?: number;
            /**
             * @description 옵션 그룹명
             * @example 샌드위치 선택 / 김밥 선택
             */
            name?: string;
            /**
             * @description 필수 선택 여부
             * @example true
             */
            isRequired?: boolean;
            /**
             * @description 다중 선택 가능 여부
             * @example false
             */
            isMultiple?: boolean;
            /** @description 세부 옵션 목록 */
            options?: components["schemas"]["OptionDTO"][];
        };
        StoreSearchCondition: {
            /**
             * @description 텍스트 검색어
             * @example 데이브런치
             */
            keyword?: string;
            /**
             * @description 위치 필터
             * @example 마포구
             * @enum {string}
             */
            region?: "GANGNAM" | "GANGDONG" | "GANGBUK" | "GANGSEO" | "GWANAK" | "GWANGJIN" | "GURO" | "GEUMCHEON" | "NOWON" | "DOBONG" | "DONGDAEMUN" | "DONGJAK" | "MAPO" | "SEODAEMUN" | "SEOCHO" | "SEONGDONG" | "SEONGBUK" | "SONGPA" | "YANGCHEON" | "YEONGDEUNGPO" | "YONGSAN" | "EUNPYEONG" | "JONGNO" | "JUNG" | "JUNGNANG";
            /**
             * Format: date
             * @description 픽업 날짜 필터 (단일 선택)
             * @example 2026-04-23
             */
            pickupDate?: string;
            /**
             * @description 픽업 시간 필터 (다중 선택 가능)
             * @example [
             *       "12:00:00",
             *       "13:00:00"
             *     ]
             */
            pickupTimes?: string[];
            /**
             * Format: int32
             * @description 주문 수량 필터
             * @example 50
             */
            quantity?: number;
            /**
             * Format: int32
             * @description 1인당 예산 필터
             * @example 10000
             */
            budget?: number;
            /**
             * @description 카테고리 필터
             * @example 샌드위치&김밥
             * @enum {string}
             */
            category?: "SANDWICH_KIMBAP" | "DESSERT" | "BEVERAGE";
            /**
             * @description 정렬 기준(기본값: NONE - 가나다 순)
             * @example NONE
             * @enum {string}
             */
            sortType?: "NONE" | "DISCOUNT_DESC" | "PRICE_ASC" | "PRICE_DESC" | "ORDER_DESC" | "RATING_DESC";
        };
        ApiResponseStoreListDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["StoreListDTO"];
        };
        StoreCardDTO: {
            /**
             * Format: int64
             * @description 가게 ID
             * @example 1
             */
            storeId?: number;
            /**
             * @description 대표 이미지
             * @example https://...
             */
            imageUrl?: string;
            /**
             * @description 가게명
             * @example 데이브런치
             */
            name?: string;
            /**
             * @description 카테고리
             * @example 샌드위치&김밥
             */
            category?: string;
            /**
             * Format: int32
             * @description 최소 가격
             * @example 7000
             */
            minPrice?: number;
            /**
             * Format: int32
             * @description 최대 가격
             * @example 12000
             */
            maxPrice?: number;
            /**
             * @description 연락처
             * @example 051-1234-5678
             */
            phoneNumber?: string;
            /**
             * Format: double
             * @description 별점
             * @example 4.7
             */
            rating?: number;
            /**
             * @description 픽업 시간
             * @example 10:00 ~ 17:00
             */
            pickupTimeRange?: string;
        };
        StoreListDTO: {
            /**
             * Format: int64
             * @description 검색된 전체 가게 수
             * @example 42
             */
            totalElements?: number;
            /** @description 가게 카드 리스트 */
            storeList?: components["schemas"]["StoreCardDTO"][];
        };
        ApiResponseOrderListResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OrderListResponse"];
        };
        OrderCardDTO: {
            /**
             * Format: int64
             * @description 주문 고유 ID
             * @example 1
             */
            orderId?: number;
            /**
             * Format: int64
             * @description 가게 ID
             * @example 1
             */
            storeId?: number;
            /**
             * @description 가게명
             * @example 데이브런치
             */
            storeName?: string;
            /**
             * @description 가게 대표 이미지
             * @example https://...
             */
            storeImageUrl?: string;
            /**
             * Format: date
             * @description 주문 생성 날짜
             * @example 2026-04-20
             */
            orderDate?: string;
            /**
             * @description 주문 생성 시간
             * @example 22:30:00
             */
            orderTime?: string;
            /**
             * Format: date
             * @description 픽업 예정 날짜
             * @example 2026-04-23
             */
            pickupDate?: string;
            /**
             * @description 픽업 예정 시간
             * @example 10:00:00
             */
            pickupTime?: string;
            /**
             * @description 주문 메뉴 요약명
             * @example 반반 세트 외 1개
             */
            menuSummary?: string;
            /**
             * Format: int32
             * @description 할인 전 원가
             * @example 392000
             */
            totalOriginalPrice?: number;
            /**
             * Format: int32
             * @description 최종 결제 금액
             * @example 372400
             */
            paymentAmount?: number;
            /**
             * @description 주문 상태
             * @example PENDING
             * @enum {string}
             */
            orderStatus?: "PENDING" | "PAID" | "ACCEPTED" | "COMPLETED" | "REJECTED" | "CANCELLED";
            /**
             * @description 결제 방식 (선결제/현장결제)
             * @example PREPAID
             * @enum {string}
             */
            paymentMethod?: "PREPAID" | "ON_SITE";
        };
        OrderListResponse: {
            /** @description 주문 내역 리스트 */
            orders?: components["schemas"]["OrderCardDTO"][];
            /**
             * Format: int64
             * @description 전체 주문 개수
             * @example 5
             */
            totalElements?: number;
            /**
             * @description 다음 페이지 존재 여부 (무한 스크롤용)
             * @example true
             */
            hasNext?: boolean;
        };
        ApiResponseOrderDetailResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["OrderDetailResponse"];
        };
        OrderDetailItemDTO: {
            /**
             * @description 메뉴명
             * @example 반반 세트
             */
            menuName?: string;
            /**
             * Format: int32
             * @description 수량
             * @example 56
             */
            quantity?: number;
        };
        OrderDetailResponse: {
            /**
             * Format: int64
             * @description 주문 고유 ID)
             * @example 1
             */
            orderId?: number;
            /**
             * @description 주문 상태
             * @example PENDING
             * @enum {string}
             */
            orderStatus?: "PENDING" | "PAID" | "ACCEPTED" | "COMPLETED" | "REJECTED" | "CANCELLED";
            /**
             * @description 주문자
             * @example 김동욱
             */
            customerName?: string;
            /**
             * @description 연락처
             * @example 010-1234-5678
             */
            customerPhone?: string;
            /**
             * Format: date
             * @description 픽업 날짜
             * @example 2026-04-23
             */
            pickupDate?: string;
            /**
             * @description 픽업 시간
             * @example 10:00:00
             */
            pickupTime?: string;
            /** @description 주문 메뉴 및 수량 목록 */
            items?: components["schemas"]["OrderDetailItemDTO"][];
            /**
             * Format: int32
             * @description 총 금액 (할인 적용된 최종 결제액)
             * @example 372400
             */
            paymentAmount?: number;
            /**
             * @description 결제 상태
             * @example ON_SITE
             * @enum {string}
             */
            paymentMethod?: "PREPAID" | "ON_SITE";
            /**
             * Format: date
             * @description 주문 날짜
             * @example 2026-04-20
             */
            orderDate?: string;
            /**
             * @description 주문 시간
             * @example 17:30:00
             */
            orderTime?: string;
        };
        ApiResponseAuthenticatedMemberResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["AuthenticatedMemberResponse"];
        };
        AuthenticatedMemberResponse: {
            /** Format: int64 */
            memberId?: number;
            /** @enum {string} */
            memberType?: "CUSTOMER" | "BUSINESS";
            /** @enum {string} */
            memberStatus?: "SIGNUP_IN_PROGRESS" | "ACTIVE" | "BUSINESS_PENDING" | "BUSINESS_REJECTED" | "WITHDRAWN";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signupCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerSignupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCustomerSignupResponse"];
                };
            };
        };
    };
    signupCommon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommonSignupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCommonSignupResponse"];
                };
            };
        };
    };
    signupBusiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessSignupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBusinessSignupResponse"];
                };
            };
        };
    };
    sendCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneVerificationSendRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePhoneVerificationResponse"];
                };
            };
        };
    };
    confirmCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneVerificationConfirmRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePhoneVerificationResponse"];
                };
            };
        };
    };
    confirmPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentConfirmRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaymentConfirmResponse"];
                };
            };
        };
    };
    getOrderList: {
        parameters: {
            query?: {
                /** @description 정렬 필터 타입 */
                filter?: "ALL" | "PAID" | "ACCEPTED" | "COMPLETED" | "REJECTED";
                /** @description 마지막으로 조회된 주문 ID (최초 조회 시 생략) */
                lastOrderId?: number;
                /** @description 한 번에 가져올 데이터 개수 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderListResponse"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderCreateResponse"];
                };
            };
        };
    };
    addCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemAddRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCartListResponse"];
                };
            };
        };
    };
    calculateCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartCalculateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCartCalculateResponse"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenReissueResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLogoutResponse"];
                };
            };
        };
    };
    rejectOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 거절할 주문 ID */
                orderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRejectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderStatusChangeResponse"];
                };
            };
        };
    };
    completePickup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 픽업 완료 처리할 주문 ID */
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderStatusChangeResponse"];
                };
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 취소할 주문 ID */
                orderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCancelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderCancelResponse"];
                };
            };
        };
    };
    acceptOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 승인할 주문 ID */
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderStatusChangeResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    getTerms: {
        parameters: {
            query: {
                targetType: "COMMON" | "CUSTOMER" | "BUSINESS";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTermsResponse"];
                };
            };
        };
    };
    getStoreDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseStoreDetailResponse"];
                };
            };
        };
    };
    getPickupTimes: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                storeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePickupTimeResponse"];
                };
            };
        };
    };
    getStoreMenus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMenuListResponse"];
                };
            };
        };
    };
    searchStores: {
        parameters: {
            query: {
                condition: components["schemas"]["StoreSearchCondition"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseStoreListDTO"];
                };
            };
        };
    };
    getOrderDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 조회할 주문 ID */
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderDetailResponse"];
                };
            };
        };
    };
    getCartList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCartListResponse"];
                };
            };
        };
    };
    authorize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthenticatedMemberResponse"];
                };
            };
        };
    };
    deleteCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartItemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
}
