export const MOCK_ORDERS = [
  {
    orderId: 1,
    status: 'pending' as const,
    isReorder: false,
    groupName: 'CEOS 데모데이',
    customerName: '안세빈',
    pickupDate: '6월 15일(월) 오전 10:00',
    paymentAmount: 325000,
    paymentMethod: 'PREPAID' as const,
    items: [
      { menuName: '반반 세트', quantity: 55 },
      { menuName: '특별 세트', quantity: 15 },
    ],
    orderDate: '2026-06-15T10:00:00',
    pastStatus: undefined,
  },
  {
    orderId: 2,
    status: 'pending' as const,
    isReorder: true,
    groupName: 'CEOS 데모데이',
    customerName: '안세빈',
    pickupDate: '6월 15일(월) 오전 10:00',
    paymentAmount: 325000,
    paymentMethod: 'ON_SITE' as const,
    items: [{ menuName: '반반 세트', quantity: 55 }],
    orderDate: '2026-06-15T10:00:00',
    pastStatus: undefined,
  },
  {
    orderId: 3,
    status: 'pending' as const,
    isReorder: true,
    groupName: 'CEOS 데모데이',
    customerName: '안세빈',
    pickupDate: '6월 15일(월) 오전 10:00',
    paymentAmount: 325000,
    paymentMethod: 'ON_SITE' as const,
    items: [{ menuName: '반반 세트', quantity: 55 }],
    orderDate: '2026-06-15T10:00:00',
    pastStatus: undefined,
  },
  {
    orderId: 4,
    status: 'confirmed' as const,
    isReorder: true,
    groupName: 'CEOS 데모데이',
    customerName: '안세빈',
    pickupDate: '6월 15일(월) 오전 10:00',
    paymentAmount: 325000,
    paymentMethod: 'ON_SITE' as const,
    items: [
      { menuName: '반반 세트', quantity: 55 },
      { menuName: '특별 세트', quantity: 15 },
    ],
    orderDate: '2026-06-15T10:00:00',
    pastStatus: undefined,
  },
  {
    orderId: 5,
    status: 'confirmed' as const,
    isReorder: true,
    groupName: 'CEOS 데모데이',
    customerName: '안세빈',
    pickupDate: '6월 15일(월) 오전 10:00',
    paymentAmount: 325000,
    paymentMethod: 'PREPAID' as const,
    items: [{ menuName: '반반 세트', quantity: 55 }],
    orderDate: '2026-06-15T10:00:00',
    pastStatus: undefined,
  },
  {
    orderId: 6,
    status: 'past' as const,
    isReorder: true,
    groupName: 'CEOS 데모데이',
    customerName: '안세빈',
    pickupDate: '6월 15일(월) 오전 10:00',
    paymentAmount: 325000,
    paymentMethod: 'ON_SITE' as const,
    items: [{ menuName: '반반 세트', quantity: 55 }],
    orderDate: '2026-06-15T10:00:00',
    pastStatus: 'REJECTED' as const,
  },
  {
    orderId: 7,
    status: 'past' as const,
    isReorder: false,
    groupName: 'CEOS 데모데이',
    customerName: '안세빈',
    pickupDate: '6월 15일(월) 오전 10:00',
    paymentAmount: 325000,
    paymentMethod: 'PREPAID' as const,
    items: [
      { menuName: '반반 세트', quantity: 55 },
      { menuName: '특별 세트', quantity: 15 },
    ],
    orderDate: '2026-06-15T10:00:00',
    pastStatus: 'CANCELLED' as const,
  },
  {
    orderId: 8,
    status: 'past' as const,
    isReorder: true,
    groupName: 'CEOS 데모데이',
    customerName: '안세빈',
    pickupDate: '6월 15일(월) 오전 10:00',
    paymentAmount: 325000,
    paymentMethod: 'ON_SITE' as const,
    items: [{ menuName: '반반 세트', quantity: 55 }],
    orderDate: '2026-06-15T10:00:00',
    pastStatus: 'PICKUP_COMPLETED' as const,
  },
];
